// frontend/angular/app.component.ts
// Why this file exists:
// - Minimal Angular UI that calls http://localhost:5101
// - Shows: ngModel, *ngFor, click handler, toggle done, simple toast

import { Component } from "@angular/core";
import { HttpClient } from "@angular/common/http";

const API = "http://localhost:5101";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
})
export class AppComponent {
  titleInput = "";
  toast = false;

  tasks: any[] = [];

  constructor(private http: HttpClient) {}

  showToast() {
    this.toast = true;
    setTimeout(() => (this.toast = false), 900);
  }

  load() {
    this.http.get<any[]>(`${API}/tasks`).subscribe((data) => (this.tasks = data));
  }

  addTask() {
    this.http
      .post(`${API}/tasks`, { title: this.titleInput })
      .subscribe(() => {
        this.titleInput = "";
        this.showToast();
        this.load();
      });
  }

  toggleDone(id: number) {
    this.http.patch(`${API}/tasks/${id}/done`, {}).subscribe(() => {
      this.showToast();
      this.load();
    });
  }

  ngOnInit() {
    this.load();
  }
}

<!-- Why this file exists:
     - Minimal Angular template shape -->

<div style="padding: 16px; font-family: sans-serif;">
  <h2>Tasks</h2>

  <input [(ngModel)]="titleInput" placeholder="Task title" />
  <button (click)="addTask()" [disabled]="!titleInput.trim()">Add</button>

  <div *ngIf="toast" style="margin-top: 8px;">
    Saved!
  </div>

  <ul>
    <li *ngFor="let t of tasks">
      <label style="cursor: pointer;">
        <input type="checkbox" [checked]="t.done" (change)="toggleDone(t.id)" />
        <span style="margin-left: 8px;" [style.textDecoration]="t.done ? 'line-through' : 'none'">
          {{ t.title }}
        </span>
      </label>
    </li>
  </ul>
</div>

// frontend/react/App.jsx
/*
Why this file exists:
- Minimal working React UI that calls the backend at http://localhost:5101
- Shows: state, form, list, toggle done, simple toast (no libraries)
*/

import { useEffect, useState } from "react";

const API = "http://localhost:5101";

export default function App() {
  const [tasks, setTasks] = useState([]);
  const [title, setTitle] = useState("");
  const [toast, setToast] = useState(false);

  function showToast() {
    setToast(true);
    setTimeout(() => setToast(false), 900);
  }

  async function load() {
    const res = await fetch(`${API}/tasks`);
    setTasks(await res.json());
  }

  async function addTask(e) {
    e.preventDefault();

    await fetch(`${API}/tasks`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title }),
    });

    setTitle("");
    showToast();
    load();
  }

  async function toggleDone(id) {
    await fetch(`${API}/tasks/${id}/done`, { method: "PATCH" });
    showToast();
    load();
  }

  useEffect(() => { load(); }, []);

  return (
    <div style={{ padding: 16, fontFamily: "sans-serif" }}>
      <h2>Tasks</h2>

      <form onSubmit={addTask}>
        <input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Task title"
        />
        <button type="submit" disabled={!title.trim()}>
          Add
        </button>
      </form>

      {toast && <div style={{ marginTop: 8 }}>Saved!</div>}

      <ul>
        {tasks.map((t) => (
          <li key={t.id}>
            <label style={{ cursor: "pointer" }}>
              <input
                type="checkbox"
                checked={!!t.done}
                onChange={() => toggleDone(t.id)}
              />
              <span style={{ marginLeft: 8, textDecoration: t.done ? "line-through" : "none" }}>
                {t.title}
              </span>
            </label>
          </li>
        ))}
      </ul>
    </div>
  );
}
